manifest_file:
  file_path: /data/flight_manifest/flight-manifest.csv
doc_intelligence:
  custom_models:
    boarding_pass_1: 591e01b4-b8ce-4c87-a3f2-53da7a437a01
video_indexer:
  video_path: 
face_api:
  recognitionModel: recognition_03
  returnFaceLandmarks: false
  maxNumOfCandidatesReturned: 10
  confidenceThreshold: 0.7
custom_vision:
  domain_type: ObjectDetection
  domain_name: General (compact)
  project_id:
  project_name:
  iteration_id:
  publish_iteration_name:
  folder_path: 
  platform: TensorFlow
  flavor: TensorFlowLite
app:
  upload_folder: src/app/uploads

